baseurl = "http://yaichi.me/"
title = "王丹"
theme = "portfolio"
languageCode = "zh-CN"
# Enable comments by entering your Disqus shortname
disqusShortname = "yaichi"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  resourceurl ="http://pburq0mjh.bkt.clouddn.com/"
  staticurl = "http://pbwlisdix.bkt.clouddn.com/"
  copyright = "&copy;2018 Yaichi"
  sidebarAbout = [
    "五年互联网产品设计经验",
    "爱好阅读、音乐、绘画，现居上海"
  ]
  keywords="产品经理，设计，UI，平面设计，UI 设计，工作，互联网"
  description="擅长 B 端产品设计、项目管理，爱好阅读、音乐、绘画"
  # Nav links in the side bar
  [[params.navlinks]]
  name = "工作项目"
  url = "projects/"
  
  [[params.navlinks]]
  name = "绘画"
  url = "painting/"
  home = true

  [[params.navlinks]]
  name = "视频"
  url = "video/"

  [[params.navlinks]]
  name = "关于我"
  url = "about/"

  [params.social]
  email         = "antsicy@126.com"
  wechat         = "http://pburq0mjh.bkt.clouddn.com/wechat.png"